SM-12 Logging
spryker-middleware/process pull request #5
Opened 2017-12-18 15:00 UTC by valerio8787

2017-12-19 15:41 UTC, lazystar commented on src/SprykerMiddleware/Zed/Process/Business/Log/Config/MiddlewareLoggerConfig.php
> +        $streamHandler = new StreamHandler(
Do we have preference for all these instantiations? Should't we keep this configurable from the outside? Meaning that we should inject this configuration.

2017-12-19 15:41 UTC, lazystar commented on src/SprykerMiddleware/Zed/Process/Business/Log/Config/MiddlewareLoggerConfig.php
> +        $formatter = new LogstashFormatter(static::NAME);
Will this logger remain hardwired to this format?

2017-12-19 15:41 UTC, lazystar commented on src/SprykerMiddleware/Zed/Process/Business/Log/Config/MiddlewareLoggerConfig.php
> +    protected function createStreamHandler(): StreamHandler
The name indicates this should be in a module factory.

2017-12-19 15:41 UTC, lazystar commented on src/SprykerMiddleware/Zed/Process/Business/Log/Config/MiddlewareLoggerConfig.php
> +    protected function createConsoleStreamHandler(): StreamHandler
The name indicates this should be in a module factory.

2017-12-19 15:41 UTC, lazystar commented on src/SprykerMiddleware/Zed/Process/Business/ProcessFacade.php
> +    public function map(array $payload, MapInterface $map, LoggerInterface $logger): array
I have to hand around the logger everywhere myself? 🤔

2017-12-19 15:41 UTC, lazystar commented on src/SprykerMiddleware/Zed/Process/Communication/ProcessCommunicationFactory.php
> +    use LoggerTrait;
What is this used for?

2017-12-20 12:42 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Process/Communication/ProcessCommunicationFactory.php
> +    use LoggerTrait;
@lazystar LoggerTrait is used for getting of  configured Logger. getLogger() method came from it

2017-12-20 13:02 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Process/Business/ProcessFacade.php
> +    public function map(array $payload, MapInterface $map, LoggerInterface $logger): array
@lazystar it is horizontal dependency, we discussed it with @vlunov-spryker, and decided that we haven't another choice

2017-12-20 13:05 UTC, valerio8787 commented on src/SprykerMiddleware/Zed/Process/Business/Log/Config/MiddlewareLoggerConfig.php
> +    protected function createStreamHandler(): StreamHandler
@lazystar It is a basic logger configuration that provided only as example. Each process can provide own logger configuration. In this case i think that possibility to configure all logger parameters in one place can do it less complicated, than injecting a lot of dependencies (processors, formatter, handlers and Config).

2017-12-21 15:00 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Business/Log/Config/MiddlewareLoggerConfig.php
> +    const NAME = 'SprykerMiddleware';
CHANNEL_NAME?

2017-12-21 15:53 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Business/Log/Config/MiddlewareLoggerConfig.php
> +    protected function createStreamHandler(): StreamHandler
@valerio8787 then the name should be MonologLoggerConfig.
This implementation is too specific. So then it should be clarified as a spec-impl or become more generic (through factory, adapters etc).

2017-12-21 16:09 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Business/Mapper/Mapper.php
> +        return $this->payloadManager->setValue($result, $key, $mappedValue);
Please don't use setter prefix (set-) to modify passing values. Setter should return void or $this.

2017-12-21 16:12 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Business/Pipeline/Stage/Stage.php
> +            'stage' => get_class($this->stagePlugin),
Could you envelop it in a protected function?

2017-12-21 16:15 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Business/ProcessFacade.php
> +    public function map(array $payload, MapInterface $map, LoggerInterface $logger): array
Facade methods should take/return only primitives or transfer objects. Dependencies through facade are now allowed. 
@vlunov-spryker could you use factory?

2017-12-21 16:16 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Business/ProcessFacadeInterface.php
> +     * @param \Psr\Log\LoggerInterface $logger
Please mark facade methods as API.

2017-12-21 16:16 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Business/ProcessFacade.php
> +     * @param \Psr\Log\LoggerInterface $logger
Please inherit doc-block from the interface.

2017-12-21 16:18 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Business/Translator/Translator.php
> +            'Translation',
Const?

2017-12-21 16:19 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Communication/Console/ProcessConsole.php
> +            'f',
Const. Eg OPTION_LOG_LEVEL_SHORTCUT = 'f'

2017-12-21 16:20 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Communication/Console/ProcessConsole.php
> +        $offset = $input->getOption(self::OPTION_ITERATOR_OFFSET) ?: 0;
static?

2017-12-21 16:21 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Communication/ProcessCommunicationFactory.php
> +    use LoggerTrait;
@valerio8787 please make sure there is not business logic in the factory. And move logger BL to a delegated business model.

2017-12-21 16:23 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Communication/ProcessCommunicationFactory.php
> +    protected function getProcessLoggerConfigList(): array
Configuration should come from a special delegated class - ProcessConfig => AbstractBundleConfig

2017-12-21 16:24 UTC, PhilinTv requested changes
Please fix/answer comments.

2017-12-22 14:45 UTC, merged