SM-57 Stream implementation
spryker-middleware/process pull request #9
Opened 2017-12-27 09:33 UTC by valerio8787

2017-12-29 10:41 UTC, ievgenvarava commented on src/SprykerMiddleware/Service/Process/Model/JsonStreamService.php
> +        return json_decode(fgets($stream), true);
Do we need this service to actually support streams? https://www.salsify.com/blog/engineering/json-streaming-parser-for-php

2018-01-02 14:13 UTC, ievgenvarava commented on src/SprykerMiddleware/Zed/Process/Business/Stream/JsonStream.php
> +    public function stream_seek($offset, $whence = SEEK_SET)
it doesn't seem that $this->position is modified, is it?

2018-01-02 14:19 UTC, ievgenvarava commented on src/SprykerMiddleware/Zed/Process/Business/Stream/JsonStream.php
> +    public function stream_seek($offset, $whence = SEEK_SET)
$offset is ignored.

2018-01-02 14:49 UTC, ievgenvarava commented on src/SprykerMiddleware/Zed/Process/Business/Stream/JsonStream.php
> +        $result = fseek($this->subhandle, 0, $whence);
is there any reason to fseek again if position is ignored on next call? passed $offset is ignored anyway

2018-01-02 15:01 UTC, ievgenvarava commented on src/SprykerMiddleware/Zed/Process/Business/Stream/JsonStream.php
> +        $result = fseek($this->subhandle, 0, $whence);
further inconsistency: http://php.net/manual/en/streamwrapper.stream-seek.php claims that returned value has to be boolean (true if position was updated), but fseek() would return 0 on success: http://php.net/manual/en/function.fseek.php

2018-01-02 15:13 UTC, ievgenvarava commented on src/SprykerMiddleware/Zed/Process/Business/Stream/JsonStream.php
> +            $this->subhandle = fopen($parts['host'] . ':' . $parts['path'], $mode, $options);
third parameter for fopen() is use_include_path which is boolean, looks like it's not correct to mix it up with options flags

2018-01-02 15:23 UTC, ievgenvarava commented on src/SprykerMiddleware/Zed/Process/Business/Stream/JsonStream.php
> +            $this->subhandle = fopen($parts['host'] . ':' . $parts['path'], $mode, $options, $opened_path);
fopen() returns false on error, but this will be assigned to $this->subhandle

2018-01-02 15:27 UTC, ievgenvarava commented on src/SprykerMiddleware/Zed/Process/Business/Stream/JsonStream.php
> +        return true;
there is no false value returned on failure. Also, STREAM_REPORT_ERRORS option is ignored.

2018-01-02 16:14 UTC, ievgenvarava commented on src/SprykerMiddleware/Zed/Process/Business/Stream/JsonStream.php
> +     * @return void
Should return the number of bytes that were successfully stored, or 0 if none could be stored.

2018-01-02 16:26 UTC, ievgenvarava requested changes
JsonStream has a lot of deviations from recommended StreamWrapper

2018-01-03 10:26 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Business/Stream/JsonStream.php
> +    public function stream_close()
Underscores.

2018-01-03 10:27 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/ProcessDependencyProvider.php
> +        $container = $this->addServices($container);
Each subject in a sep method.

2018-01-03 10:28 UTC, PhilinTv commented on src/SprykerMiddleware/Zed/Process/Communication/Console/ProcessConsole.php
> +            'o',
Shortcuts in consts

2018-01-30 11:55 UTC, merged